//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals_Review.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitat
    {
        public int Habitat_ID { get; set; }
        public string Habitat_Type { get; set; }
        public string Description { get; set; }
        public int Animals_ID { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
