//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals_Review.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int Media_ID { get; set; }
        public Nullable<int> Animal_ID { get; set; }
        public string Media_Type { get; set; }
        public string URL { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual User User { get; set; }
    }
}
